### ISSUE TITLE
constant `SCOPES` is not defined

### ISSUE THREAD

**Issue by elmarsan** [sergiogragera/whatsapp-calendar-gpt-bot#1]
Hey! 

When I start the program, the authentication process cannot be done because `SCOPS` constant is missing.
https://github.com/sergiogragera/whatsapp-calendar-gpt-bot/blob/b2ef382ac0e58bbf7490685d5cba8b23ccae9cae/calendar.js#L39

**Comment by sergiogragera** [comment]
Thank you. I deleted comments and removed some wrong line. Now is fixed by this [commit](https://github.com/sergiogragera/whatsapp-calendar-gpt-bot/commit/245536eb4c694c4d048c673e3463d44be8621217)

And you can get a calendar code reference from [here](https://developers.google.com/calendar/api/quickstart/nodejs)
